### ISSUE TITLE
트림하기

### ISSUE THREAD

**Issue by nsr1349** [team-moabam/moabam-FE#489]
# ✨ Feature
## Description
유저 에딧 트림하기

## To-do
- [ ] 유저 에딧 트림하기

## 기타
따로 팀원과 상의가 필요한 부분들을 적는 공간입니다.

https://github.com/orgs/team-moabam/discussions/번호

**Comment by chasj0326** [comment]
const trimedNickName = nickname.replaceAll(' ', '')
if (trimedNickName) modifyMemberRequest['nickname'] = trimedNickName;

요러케 해야할둣합니다 ㅠ.ㅠ
